

-- This file is generated by the neblua bundler
-- https://github.com/Tsukina-7mochi/neblua

    local function snapshot(target)
        local addedKeys = {}
        setmetatable(target, {
            __newindex = function (t, k, v)
                table.insert(addedKeys, k)
                rawset(t, k, v)
            end,
        })

        local rollback = function()
            for _, k in ipairs(addedKeys) do
                rawset(target, k, nil)
            end
            setmetatable(target, nil)
        end

        return rollback
    end

    local rollbackLoaded = snapshot(package.loaded)
    local rollbackPreload = snapshot(package.preload)
    local rollbackSearchers = snapshot(package.searchers)


package.nebluaModule = {}



package.nebluaModule["./entry/iconCursor.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
package.manifest = {
    name = "aseprite-scripts/icon-and-cursor",
    description = "Export sprite as windows icon and cursor.",
    version = "v0.2.0",
    author = "Mooncake Sugar",
    license = "MIT",
    homepage = "https://github.com/Tsukina-7mochi/aseprite-scripts/blob/master/icon-and-cursor/",
}

if not app then
    return
end

require("app.iconCursor.init").main()

    end
}

package.nebluaModule["./app/iconCursor/init.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
local dialog = require("app.iconCursor.dialog")
local parameter = require("app.iconCursor.parameter")
local createIcon = require("app.iconCursor.icon").create
local createAnimCursor = require("app.iconCursor.anim-cursor").create
local util = require("pkg.asepriteUtil")

local function getParamsFromArgs ()
    local params = parameter.default(app.sprite)
    if app.params.filetype ~= nil then
        params.filetype = app.params.filetype
    end
    if app.params.filename ~= nil then
        params.filename = app.params.filename
    end
    if app.params["hot-spot-x"] ~= nil then
        params.hotSpotX = assert(tonumber(app.params["hot-spot-x"]))
    end
    if app.params["hot-spot-y"] ~= nil then
        params.hotSpotY = assert(tonumber(app.params["hot-spot-y"]))
    end
    if app.params.framerate ~= nil then
        params.framerate = assert(tonumber(app.params.framerate))
    end
    if app.params.layers ~= nil then
        params.layers = app.params.layers
    end
    if app.params.tag ~= nil then
        params.tag = tonumber(app.params.tag) or app.params.tag
    end

    local valid, validationError = parameter.validate(params, app.sprite)
    if not valid then
        error("Error: " .. (validationError or "Unknown validation error"))
    end

    return params
end

local function getParams ()
    if app.isUIAvailable then
        return dialog.show(app.sprite)
    else
        return getParamsFromArgs()
    end
end

local function main ()
    if app.apiVersion < 1 then
        util.alert({ text = "This script requires Aseprite v1.2.10-beta3 or above." })
        return
    end

    local sprite = app.sprite
    if sprite == nil then
        util.alert({ text = "There is no active sprite to export." })
        return
    end

    local params = getParams()
    if params == nil then
        return
    end

    local targetLayers = {}
    if params.layers == "selected" then
        targetLayers = util.sprite.getSelectedLayers(sprite)
    elseif params.layers == "visible" then
        targetLayers = util.sprite.getVisibleLayers(sprite)
    end

    local targetFrames = {}
    if params.tag == nil then
        targetFrames = sprite.frames
    elseif type(params.tag) == "number" then
        targetFrames = { sprite.frames[params.tag] }
    else
        local tag = util.sprite.getTag(sprite, params.tag)
        if tag == nil then
            error("The specified tag was not found.")
            return
        end

        targetFrames = util.tag.getFrames(tag)
    end

    local fileData = ""
    if params.filetype == "ani" then
        fileData = createAnimCursor(params, targetLayers, targetFrames)
    else
        fileData = createIcon(params, targetLayers, targetFrames)
    end

    local file = io.open(params.filename, "wb")
    if not file then
        util.alert({ text = "Failed to open the file to export." })
        return
    end

    file:write(fileData)

    file:close()
end

return { main = main }

    end
}

package.nebluaModule["./app/iconCursor/dialog.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
local parameter = require("app.iconCursor.parameter")
local util = require("pkg.asepriteUtil")

local PROPERTY_KEY = "icon-and-cursor.dialog"
local FILETYPE_OPTIONS = {
    { option = "Icon", value = "ico", isCursor = false, isAnimated = false },
    { option = "Cursor", value = "cur", isCursor = true, isAnimated = false },
    { option = "Animated Cursor", value = "ani", isCursor = true, isAnimated = true },
}
local LAYER_OPTIONS = {
    { option = "Visible", value = "visible" },
    { option = "Selected", value = "selected" },
}
local TAG_OPTION_PREFIX = "Tag: "
local FRAME_OPTION_PREFIX = "Frame: "
local TAG_OPTION_ALL = "All Frames"

local ID = {
    filetype = "filetype",
    layers = "layers",
    tag = "tag",
    framerate = "framerate",
    hotspotX = "hotspotX",
    hotspotY = "hotspotY",
    filename = "filename",
    ok = "ok",
    cancel = "cancel",
}

---@param options { option: string, value: any }[]
---@return string[]
local function optionLabels (options)
    local labels = {}
    for _, item in ipairs(options) do
        table.insert(labels, item.option)
    end
    return labels
end

---@generic T : { option: string }
---@param options T[]
---@return T
local function getOptionEntry (options, option)
    for _, item in ipairs(options) do
        if item.option == option then
            return item
        end
    end
    return nil
end

---Creates and shows the icon/cursor export dialog
---@param sprite Sprite
---@return IconCursorParams? params Returns nil if cancelled
local function show (sprite)
    local tagOptions = { { option = TAG_OPTION_ALL, value = nil } }
    for _, tag in ipairs(sprite.tags) do
        table.insert(tagOptions, { option = TAG_OPTION_PREFIX .. tag.name, value = tag.name })
    end
    for _, frame in ipairs(sprite.frames) do
        table.insert(tagOptions, { option = FRAME_OPTION_PREFIX .. frame.frameNumber, value = frame.frameNumber })
    end

    local savedData = {}
    if sprite.properties ~= nil and type(sprite.properties[PROPERTY_KEY]) == "table" then
        savedData = sprite.properties[PROPERTY_KEY]
    end

    local defaultFiletype = FILETYPE_OPTIONS[1].option
    local defaultFilename = app.fs.filePathAndTitle(sprite.filename) .. "." .. FILETYPE_OPTIONS[1].value
    local defaultFramerate = math.floor(sprite.frames[1].duration * 60)

    local dialog = Dialog("Export Icon/Cursor")
    if dialog == nil then
        error("Failed to create dialog, UI may not be available")
    end

    local function updateVisibility ()
        local filetype = dialog.data[ID.filetype]
        local isCursor = getOptionEntry(FILETYPE_OPTIONS, filetype).isCursor
        local isAnimated = getOptionEntry(FILETYPE_OPTIONS, filetype).isAnimated
        dialog:modify({ id = ID.hotspotX, visible = isCursor })
        dialog:modify({ id = ID.hotspotY, visible = isCursor })
        dialog:modify({ id = ID.framerate, visible = isAnimated })
    end

    local function updateFilename ()
        local filename = dialog.data[ID.filename] --[[ @as string ]]
        local filetype = dialog.data[ID.filetype] --[[ @as string ]]
        local newFilename = app.fs.filePathAndTitle(filename) .. "." .. getOptionEntry(FILETYPE_OPTIONS, filetype).value
        dialog.data[ID.filename] = newFilename
        dialog:modify({ id = ID.filename, filename = newFilename })
    end

    dialog
        :combobox({
            id = ID.filetype,
            label = "File Type",
            option = savedData[ID.filetype] or defaultFiletype,
            options = optionLabels(FILETYPE_OPTIONS),
            onchange = function ()
                updateVisibility()
                updateFilename()
            end,
        })
        :combobox({
            id = ID.layers,
            label = "Layers",
            option = savedData[ID.layers] or LAYER_OPTIONS["Visible"],
            options = optionLabels(LAYER_OPTIONS),
        })
        :combobox({
            id = ID.tag,
            label = "Frames",
            option = savedData[ID.tag] or TAG_OPTION_ALL,
            options = optionLabels(tagOptions),
        })
        :number({
            id = ID.framerate,
            label = "Framerate (1/60s)",
            text = tostring(savedData[ID.framerate]) or tostring(defaultFramerate),
        })
        :number({
            id = ID.hotspotX,
            label = "Hot Spot",
            text = tostring(savedData[ID.hotspotX]) or "0",
            decimals = 0,
        })
        :number({
            id = ID.hotspotY,
            text = tostring(savedData[ID.hotspotY]) or "0",
            decimals = 0,
        })
        :separator({ text = "Output" })
        :file({
            id = ID.filename,
            label = "Filename",
            title = "Export as...",
            save = true,
            filename = savedData[ID.filename] or defaultFilename,
        })
        -- Buttons
        :button({ id = ID.ok, text = "&Export", focus = true })
        :button({ id = ID.cancel, text = "&Cancel" })

    while true do
        updateVisibility()
        dialog:show()

        -- Check if cancelled
        if not dialog.data[ID.ok] then
            return nil
        end

        -- Build params table
        local params = {
            filetype = getOptionEntry(FILETYPE_OPTIONS, dialog.data.filetype).value,
            filename = dialog.data.filename,
            hotSpotX = dialog.data.hotspotX or 0,
            hotSpotY = dialog.data.hotspotY or 0,
            framerate = dialog.data.framerate or 1,
            tag = getOptionEntry(tagOptions, dialog.data.tag).value,
            layers = getOptionEntry(LAYER_OPTIONS, dialog.data.layers).value,
        }

        -- Validate params
        local valid, validationError = parameter.validate(params, sprite)
        if valid then
            sprite.properties[PROPERTY_KEY] = dialog.data
            return params --[[@as IconCursorParams]]
        else
            util.alert({
                title = "Invalid Parameters",
                text = validationError or "Unknown validation error",
            })
        end
    end
end

return {
    show = show,
}

    end
}

package.nebluaModule["./app/iconCursor/parameter.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---Parameters for icon/cursor export
---@class IconCursorParams
---@field filetype "ico" | "cur" | "ani"
---@field filename string
---@field hotSpotX integer
---@field hotSpotY integer
---@field framerate integer
---@field tag string | integer | nil
---@field layers "visible" | "selected"

---Creates default parameters for icon/cursor export
---@param sprite Sprite
---@return IconCursorParams
local function default (sprite)
    local defaultFiletype = "ico"
    local defaultFilename = app.fs.filePathAndTitle(sprite.filename) .. "." .. defaultFiletype
    local defaultFramerate = math.floor(sprite.frames[1].duration * 60)

    return {
        filetype = defaultFiletype,
        filename = defaultFilename,
        hotSpotX = 0,
        hotSpotY = 0,
        framerate = defaultFramerate,
        showCompleted = true,
        tag = nil,
        layers = "visible",
    }
end

---Validates icon/cursor export parameters
---@param params IconCursorParams
---@param sprite Sprite
---@return boolean valid
---@return string? errorMessage
local function validate (params, sprite)
    -- Validate filetype
    if type(params.filetype) ~= "string" then
        return false, "filetype must be a string"
    end
    if params.filetype ~= "ico" and params.filetype ~= "cur" and params.filetype ~= "ani" then
        return false, "filetype must be 'ico', 'cur', or 'ani'"
    end

    -- Validate filename
    if type(params.filename) ~= "string" then
        return false, "filename must be a string"
    end
    if params.filename == "" then
        return false, "filename cannot be empty"
    end

    -- Validate hotSpotX
    if type(params.hotSpotX) ~= "number" then
        return false, "hotSpotX must be a number"
    end
    if params.hotSpotX ~= math.floor(params.hotSpotX) then
        return false, "hotSpotX must be an integer"
    end
    if params.hotSpotX < 0 then
        return false, "hotSpotX must be >= 0"
    end
    if params.hotSpotX >= sprite.width then
        return false, "hotSpotX must be < sprite width (" .. sprite.width .. ")"
    end

    -- Validate hotSpotY
    if type(params.hotSpotY) ~= "number" then
        return false, "hotSpotY must be a number"
    end
    if params.hotSpotY ~= math.floor(params.hotSpotY) then
        return false, "hotSpotY must be an integer"
    end
    if params.hotSpotY < 0 then
        return false, "hotSpotY must be >= 0"
    end
    if params.hotSpotY >= sprite.height then
        return false, "hotSpotY must be < sprite height (" .. sprite.height .. ")"
    end

    -- Validate framerate
    if type(params.framerate) ~= "number" then
        return false, "framerate must be a number"
    end
    if params.framerate ~= math.floor(params.framerate) then
        return false, "framerate must be an integer"
    end
    if params.framerate < 1 then
        return false, "framerate must be >= 1"
    end

    -- Validate tag (nil means all frames, string means specific tag, number means frame index)
    if type(params.tag) == "string" then
        if type(params.tag) ~= "string" then
            return false, "tag must be a string, integer or nil"
        end
        if params.tag == "" then
            return false, "tag cannot be empty string"
        end
        -- Validate it's a valid tag name
        local tagFound = false
        for _, tag in ipairs(sprite.tags) do
            if tag.name == params.tag then
                tagFound = true
                break
            end
        end
        if not tagFound then
            return false, "tag must be nil or a valid tag name"
        end
    elseif type(params.tag) == "number" then
        if params.tag ~= math.floor(params.tag) then
            return false, "tag must be an integer, string, or nil"
        end
        if params.tag < 1 then
            return false, "tag must be >= 1 if it's a number"
        end
        if params.tag > #sprite.frames then
            return false, "tag must be <= number of frames (" .. #sprite.frames .. ") if it's a number"
        end
    end

    -- Validate layers
    if type(params.layers) ~= "string" then
        return false, "layers must be a string"
    end
    if params.layers ~= "visible" and params.layers ~= "selected" then
        return false, "layers must be 'visible' or 'selected'"
    end

    return true, nil
end

return {
    default = default,
    validate = validate,
}

    end
}

package.nebluaModule["./app/iconCursor/icon.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
local bitmaps = require("pkg.bitmap")
local pack = require("pkg.string..pack")
local util = require("pkg.asepriteUtil")

---@param filetype "ico" | "cur" | "ani"
---@param numImages integer
---@return string
local function createFileHeader (filetype, numImages)
    -- icon: 1, cursor: 2
    local resourceType = 1
    if filetype == "cur" or filetype == "ani" then
        resourceType = 2
    end

    return table.concat({
        pack.u16LE(0), -- reserved
        pack.u16LE(resourceType),
        pack.u16LE(numImages),
    }, "")
end

---@param width integer
---@param height integer
---@param hotSpotX integer
---@param hotSpotY integer
---@param imageDataSize integer
---@param imageDataOffset integer
---@return string
local function createIconHeader (width, height, hotSpotX, hotSpotY, imageDataSize, imageDataOffset)
    return table.concat({
        pack.u8(width),
        pack.u8(height),
        pack.u8(0), -- number of colors in palette (0 = no palette)
        pack.u8(0), -- reserved
        pack.u16LE(hotSpotX),
        pack.u16LE(hotSpotY),
        pack.u32LE(imageDataSize),
        pack.u32LE(imageDataOffset),
    })
end

---@param params IconCursorParams
---@param targetLayers Layer[]
---@param targetFrames Frame[]
---@return string
local function createIcon (params, targetLayers, targetFrames)
    local images = {}
    for _, frame in ipairs(targetFrames) do
        local image = util.frame.mergeLayerImages(frame, targetLayers)
        table.insert(images, image)
    end

    local fileHeader = createFileHeader(params.filetype, #targetFrames)

    ---@type string[]
    local iconHeaders = {}
    ---@type string[]
    local imageData = {}
    local dataSizeSum = 0
    for _, frame in ipairs(targetFrames) do
        local image = util.frame.mergeLayerImages(frame, targetLayers)
        local bitmap = bitmaps.createWithAlphaMask(image)

        local dataSize = #bitmap.infoHeader + #bitmap.pixelData
        -- offset = (size of file header) + (number of images) * (size of icon header = 16) + dataSizeSum
        local dataOffset = #fileHeader + (#targetFrames * 16) + dataSizeSum
        local header = createIconHeader(
            image.width,
            image.height,
            params.filetype == "ico" and 0 or params.hotSpotX,
            params.filetype == "ico" and 0 or params.hotSpotY,
            dataSize,
            dataOffset
        )

        table.insert(iconHeaders, header)
        table.insert(
            imageData,
            table.concat({
                bitmap.infoHeader,
                bitmap.pixelData,
            }, "")
        )
        dataSizeSum = dataSizeSum + dataSize
    end

    return table.concat({
        fileHeader,
        table.concat(iconHeaders),
        table.concat(imageData),
    }, "")
end

return {
    create = createIcon,
}

    end
}

package.nebluaModule["./app/iconCursor/anim-cursor.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
local createIcon = require("app.iconCursor.icon").create
local pack = require("pkg.string..pack")
local riff = require("pkg.riff")

local function createAnimHeader (numFrames, framerate)
    return table.concat({
        pack.u32LE(36), -- size of this header
        pack.u32LE(numFrames), -- numFrames
        pack.u32LE(numFrames), -- numSteps
        pack.u32LE(0), -- width (0 = use frame width)
        pack.u32LE(0), -- height (0 = use frame height)
        pack.u32LE(0), -- bitCount (0 = use frame bit depth)
        pack.u32LE(1), -- numPlanes
        pack.u32LE(framerate), -- displayRate
        pack.u32LE(1), -- flags (0b01, frames are icon data)
    })
end

---@param params IconCursorParams
---@param targetLayers Layer[]
---@param targetFrames Frame[]
---@return string
local function createAnimCursor (params, targetLayers, targetFrames)
    ---@type RiffChunk[]
    local iconChunks = {}
    for _, frame in ipairs(targetFrames) do
        local icon = createIcon(params, targetLayers, { frame })

        table.insert(iconChunks, riff.chunk("icon", icon))
    end

    local file = riff.riffChunk("ACON", {
        riff.chunk("anih", createAnimHeader(#targetFrames, params.framerate)),
        riff.listChunk("fram", iconChunks),
    })

    return tostring(file)
end

return {
    create = createAnimCursor,
}

    end
}

package.nebluaModule["./pkg/asepriteUtil/init.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
return {
    alert = require("pkg.asepriteUtil.alert"),
    frame = require("pkg.asepriteUtil.frame"),
    sprite = require("pkg.asepriteUtil.sprite"),
    tag = require("pkg.asepriteUtil.tag"),
}

    end
}

package.nebluaModule["./pkg/bitmap/init.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
local pack = require("pkg.string.pack")
local BitmapFile = require("pkg.bitmap.bitmap").BitmapFile

---Generates BMP file header
---@param fileSize integer Total file size in bytes
---@return string Binary header data
local function createFileHeader (fileSize)
    return table.concat({
        "BM", -- Signature
        pack.u32LE(fileSize), -- File size
        pack.u32LE(0), -- Reserved
        pack.u32LE(54), -- Data offset (14 + 40)
    })
end

---Generates bitmap info header
---@param width integer Image width in pixels
---@param height integer Image height in pixels
---@param bitsPerPixel integer Bits per pixel (e.g., 24 for RGB)
---@param imageSize integer Size of pixel data in bytes
---@return string Binary header data
local function createInfoHeader (width, height, bitsPerPixel, imageSize)
    return table.concat({
        pack.u32LE(40), -- Header size
        pack.i32LE(width), -- Image width
        pack.i32LE(height), -- Image height
        pack.u16LE(1), -- Planes (always 1)
        pack.u16LE(bitsPerPixel), -- Bits per pixel
        pack.u32LE(0), -- Compression (0 = uncompressed)
        pack.u32LE(imageSize), -- Image size
        pack.i32LE(0), -- X pixels per meter (0 = not specified)
        pack.i32LE(0), -- Y pixels per meter (0 = not specified)
        pack.u32LE(0), -- Colors used (0 = all colors)
        pack.u32LE(0), -- Important colors (0 = all important)
    })
end

---Encodes image pixels to BMP format
---Converts RGB to BGR, processes bottom-to-top, adds row padding
---@param image Image Aseprite Image object
---@return string Binary pixel data
local function encodePixels (image)
    local width = image.width
    local height = image.height
    local padding = (4 - (width * 3) % 4) % 4
    local rows = {}

    -- Process rows from bottom to top
    for y = height - 1, 0, -1 do
        local row = {}

        for x = 0, width - 1 do
            local pixel = image:getPixel(x, y)

            -- Store as BGR
            table.insert(row, pack.u8(app.pixelColor.rgbaB(pixel)))
            table.insert(row, pack.u8(app.pixelColor.rgbaG(pixel)))
            table.insert(row, pack.u8(app.pixelColor.rgbaR(pixel)))
        end

        -- Add padding bytes to align row to 4-byte boundary
        table.insert(row, ("\x00"):rep(padding))

        table.insert(rows, table.concat(row))
    end

    return table.concat(rows)
end

---Encodes image alpha pixels to BMP 1-bit image data
---Converts RGB to BGR, processes bottom-to-top, adds row padding
---@param image Image Aseprite Image object
---@return string Binary pixel data
local function encodeAlphaMask (image)
    local width = image.width
    local height = image.height

    -- Calculate row padding to align to 4-byte boundary
    local bitsPerRow = width
    local bytesPerRow = math.ceil(bitsPerRow / 8)
    local padding = (4 - (bytesPerRow % 4)) % 4

    local maskData = ""

    -- Process rows from bottom to top (BMP format)
    for y = height - 1, 0, -1 do
        local mask = 0
        local bitCount = 0

        -- Process pixels from left to right
        for x = 0, width - 1 do
            local pixel = image:getPixel(x, y)
            local alpha = app.pixelColor.rgbaA(pixel)

            -- Set bit to 1 if pixel is transparent (alpha == 0)
            local transparentBit = (alpha == 0) and 1 or 0

            -- Pack bit into current byte (MSB first)
            mask = (mask << 1) | transparentBit
            bitCount = bitCount + 1

            -- When we've packed 8 bits, write the byte
            if bitCount == 8 then
                maskData = maskData .. pack.u8(mask)
                mask = 0
                bitCount = 0
            end
        end

        -- Handle remaining bits in the row (if width is not multiple of 8)
        if bitCount ~= 0 then
            -- Shift remaining bits to MSB position
            mask = mask << (8 - bitCount)
            maskData = maskData .. pack.u8(mask)
        end

        -- Add padding bytes to align row to 4-byte boundary
        maskData = maskData .. ("\x00"):rep(padding)
    end

    return maskData
end

---Creates a BitmapFile from an Aseprite Image
---@param image Image Aseprite RGB Image object
---@return BitmapFile
local function create (image)
    if image.colorMode ~= ColorMode.RGB then
        error("Only RGB images are supported for BMP export")
    end

    local pixelData = encodePixels(image)
    local infoHeader = createInfoHeader(image.width, image.height, 24, #pixelData)
    local fileSize = 14 + #infoHeader + #pixelData -- 14: file header
    local fileHeader = createFileHeader(fileSize)
    return BitmapFile(fileHeader, infoHeader, pixelData)
end

---Creates a BitmapFile with alpha mask from an Aseprite Image
---@param image Image Aseprite RGB Image object
local function createWithAlphaMask (image)
    if image.colorMode ~= ColorMode.RGB then
        error("Only RGB images are supported for BMP export")
    end

    local pixelData = encodePixels(image)
    local alphaMaskData = encodeAlphaMask(image)
    local infoHeader = createInfoHeader(
        image.width,
        image.height * 2, -- double the height for alpha mask
        24,
        #pixelData -- not include alpha mask data in image size
    )
    local fileSize = 14 + #infoHeader + #pixelData + #alphaMaskData -- 14: file header
    local fileHeader = createFileHeader(fileSize)

    return BitmapFile(fileHeader, infoHeader, pixelData .. alphaMaskData)
end

return {
    create = create,
    createWithAlphaMask = createWithAlphaMask,
}

    end
}

package.nebluaModule["./pkg/string/pack.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---Packs 32-bit unsigned integer into a big-endian encoded binary string
---@param data integer
---@return string
local function u32BE (data)
    return (">I4"):pack(data)
end

---Packs 32-bit signed integer into a big-endian encoded binary string
---@param data integer
---@return string
local function i32BE (data)
    return (">i4"):pack(data)
end

---Packs 16-bit unsigned integer into a big-endian encoded binary string
---@param data integer
---@return string
local function u16BE (data)
    return (">I2"):pack(data)
end

---Packs 8-bit unsigned integer into a binary string
---@param data integer
---@return string
local function u8 (data)
    return ("B"):pack(data)
end

---Packs 32-bit unsigned integer into a little-endian encoded binary string
---@param data integer
---@return string
local function u32LE (data)
    return ("<I4"):pack(data)
end

---Packs 32-bit signed integer into a little-endian encoded binary string
---@param data integer
---@return string
local function i32LE (data)
    return ("<i4"):pack(data)
end

---Packs 16-bit unsigned integer into a little-endian encoded binary string
---@param data integer
---@return string
local function u16LE (data)
    return ("<I2"):pack(data)
end

return {
    u32BE = u32BE,
    i32BE = i32BE,
    u16BE = u16BE,
    u8 = u8,
    u32LE = u32LE,
    i32LE = i32LE,
    u16LE = u16LE,
}

    end
}

package.nebluaModule["./pkg/riff/init.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---@class RiffChunk
---@field id string
---@field data string
local __chunk = {}

local __chunkMeta = {
    ---@param self RiffChunk
    __tostring = function (self)
        local padding = ""
        if #self.data % 2 == 1 then
            padding = "\0"
        end
        return ("c4<I4"):pack(self.id, #self.data) .. self.data .. padding
    end,
}

---@param id string
---@param data string
---@return RiffChunk
local function chunk (id, data)
    local obj = { id = id, data = data }
    setmetatable(obj, __chunkMeta)
    return obj
end

---@param identifier string
---@param data RiffChunk | RiffChunk[]
---@return RiffChunk
local function riffChunk (identifier, data)
    if type(data) == "table" and #data > 0 then
        local payloads = {}
        for _, d in ipairs(data) do
            table.insert(payloads, tostring(d))
        end

        return chunk("RIFF", identifier .. table.concat(payloads))
    end

    return chunk("RIFF", identifier .. tostring(data))
end

---@param identifier string
---@param items RiffChunk[]
---@return RiffChunk
local function listChunk (identifier, items)
    local itemsStr = {}
    for _, item in ipairs(items) do
        table.insert(itemsStr, tostring(item))
    end

    return chunk("LIST", identifier .. table.concat(itemsStr))
end

return {
    chunk = chunk,
    riffChunk = riffChunk,
    listChunk = listChunk,
}

    end
}

package.nebluaModule["./pkg/asepriteUtil/alert.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
local isInteger = require("pkg.type.isType").isInteger

---@alias AlertInit { title?: string, text: string | string[], buttons?: string[] }

---Prints an alert message to the UI if available, otherwise print to the console.
---@param init AlertInit
---@return integer
local function alert (init)
    local title = init.title
    local text = init.text
    local buttons = init.buttons

    if title == nil then
        title = ""
    end
    if buttons == nil or #buttons == 0 then
        buttons = { "&Ok" }
    end

    if app.isUIAvailable then
        return app.alert({ title = title, text = text, buttons = buttons })
    else
        if title ~= "" then
            print(title)
        end

        if type(text) == "string" then
            print(text)
        else
            print(table.concat(text, "\n"))
        end

        if #buttons <= 1 then
            --Just receive keyboard input
            local _ = io.stdin:read("l")
            return 1
        else
            --Print list of buttons with index
            local len = #("" .. #buttons)
            local formatString = "%" .. len .. "d: %s"
            for i, buttonText in ipairs(buttons) do
                --Remove the first "&"
                local amp = buttonText:find("&")
                if amp ~= nil then
                    buttonText = buttonText:sub(0, amp - 1) .. buttonText:sub(amp + 1)
                end
                print(string.format(formatString, i, buttonText))
            end
            io.stdin:flush()

            while true do
                io.stdout:write("> ")
                io.stdout:flush()

                local answer = tonumber(io.stdin:read("l"))
                if isInteger(answer) and 1 <= answer and answer <= #buttons then
                    return answer --[[ @as integer ]]
                end
            end
        end
    end
end

return alert

    end
}

package.nebluaModule["./pkg/asepriteUtil/frame.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---@param frame Frame
---@param layers Layer[] | nil
---@return Image
local function mergeLayerImages (frame, layers)
    if layers == nil then
        layers = frame.sprite.layers
    end

    local result = Image(frame.sprite.width, frame.sprite.height, ColorMode.RGB)
    for _, layer in ipairs(layers) do
        local cel = layer:cel(frame)
        if cel ~= nil then
            result:drawImage(cel.image, cel.bounds.origin, layer.opacity, layer.blendMode)
        end
    end

    return result
end

return {
    mergeLayerImages = mergeLayerImages,
}

    end
}

package.nebluaModule["./pkg/asepriteUtil/sprite.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---@param sprite Sprite
---@param perdicate (fun(layer: Layer): boolean) | nil
---@return Layer[]
local function getNonGroupLayers (sprite, perdicate)
    ---@type Layer
    local result = {}

    local function traverse (layer)
        if perdicate ~= nil and not perdicate(layer) then
            return
        end

        if layer.isGroup then
            for _, child in ipairs(layer.layers) do
                traverse(child)
            end
        else
            table.insert(result, layer)
        end
    end

    for _, layer in ipairs(sprite.layers) do
        traverse(layer)
    end

    return result
end

---@param sprite Sprite
---@return Layer[]
local function getSelectedNonGroupLayers (sprite)
    return getNonGroupLayers(sprite, function (layer)
        return app.range:contains(layer)
    end)
end

---@param sprite Sprite
---@param name string
---@return Tag | nil
local function getTag (sprite, name)
    for _, tag in ipairs(sprite.tags) do
        if tag.name == name then
            return tag
        end
    end

    return nil
end

---@param sprite Sprite
---@return Layer[]
local function getVisibleLayers (sprite)
    return getNonGroupLayers(sprite, function (layer)
        return layer.isVisible
    end)
end

return {
    getNonGroupLayers = getNonGroupLayers,
    getSelectedLayers = getSelectedNonGroupLayers,
    getVisibleLayers = getVisibleLayers,
    getTag = getTag,
}

    end
}

package.nebluaModule["./pkg/asepriteUtil/tag.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---@param tag Tag
---@return Frame[]
local function getFrames (tag)
    local result = {}
    for i = tag.fromFrame.frameNumber, tag.toFrame.frameNumber do
        table.insert(result, tag.sprite.frames[i])
    end
    return result
end

return {
    getFrames = getFrames,
}

    end
}

package.nebluaModule["./pkg/bitmap/bitmap.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
---@class BitmapFile
---@field fileHeader string BMP file header (14 bytes)
---@field infoHeader string Bitmap info header (40 bytes)
---@field pixelData string Binary pixel data
---@overload fun(fileHeader: string, infoHeader: string, pixelData: string): BitmapFile
local BitmapFile = {}

---Converts the bitmap file to a binary string
---@param bitmap BitmapFile
---@return string
local function tostring (bitmap)
    return table.concat({
        bitmap.fileHeader,
        bitmap.infoHeader,
        bitmap.pixelData,
    })
end

BitmapFile.tostring = tostring

setmetatable(BitmapFile --[[ @as table ]], {
    __call = function (_, fileHeader, infoHeader, pixelData)
        local value = {
            fileHeader = fileHeader,
            infoHeader = infoHeader,
            pixelData = pixelData,
        }

        setmetatable(value, {
            __index = BitmapFile,
            __tostring = tostring,
        })

        return value
    end,
})

return { BitmapFile = BitmapFile }

    end
}

package.nebluaModule["./pkg/type/isType.lua"] = {
    line = debug.getinfo(1).currentline,
    loader = function(...)
--- Return true if given value is an integer
---@param val any
---@return boolean
local function isInteger (val)
    if type(val) ~= "number" then
        return false
    end

    return val % 1 .. "" == "0"
end

return { isInteger = isInteger }

    end
}

package.nebluaModule[debug.getinfo(1).short_src] = {
    line = 0,
    loader = nil,
}

return (function (...)
    local internalPathSeparator = "/"
    local pathSeparator = package.config:sub(1, 1)
    local templateSeparator = package.config:sub(3, 3)
    local substitutionPoint = package.config:sub(5, 5)

    local function split (str, sep)
        return str:gmatch("([^" .. sep .. "]*)")
    end

    local function collect (func)
        local result = {}
        for v in func do
            table.insert(result, v)
        end
        return result
    end

    local function normalizePath (path)
        local segments = collect(split(path, internalPathSeparator))
        local resultSegments = {}

        if segments[1] == "." then
            table.insert(resultSegments, ".")
        elseif segments[1] == "" then
            table.insert(resultSegments, "")
        elseif segments[1] == ".." then
            error("Cannot go above root directory")
        end

        for _, seg in ipairs(segments) do
            if seg == ".." then
                table.remove(resultSegments)
            elseif seg ~= "." and seg ~= "" then
                table.insert(resultSegments, seg)
            end
        end

        if segments[#segments] == "" then
            table.insert(resultSegments, "")
        end

        return table.concat(resultSegments, internalPathSeparator)
    end

    -- searches for modules in package.nebluaModule table
    local function bundlerSearcher (moduleName)
        moduleName = moduleName:gsub("%.", internalPathSeparator)

        for template in split(package.path, templateSeparator) do
            local path = template
                :gsub(pathSeparator, internalPathSeparator)
                :gsub(substitutionPoint, moduleName)

            local module = package.nebluaModule[normalizePath(path)]
            if module ~= nil and module.loader ~= nil then
                return module.loader, path
            end
        end

        return nil
    end

    if not _ENV.__NEBLUA_INSTALLED then
        -- Register the bundler searcher at the highest priority
        table.insert(package.searchers, 1, bundlerSearcher)

        -- Replace dofile
        local originalDoFile = dofile
        ---@diagnostic disable-next-line: duplicate-set-field
        _ENV.dofile = function (path)
            local loader = package.nebluaModule[path]
            if loader ~= nil and loader.loader ~= nil then
                return loader.loader()
            else
                return originalDoFile(path)
            end
        end

        -- Replace loadfile
        local originalLoadFile = loadfile
        ---@diagnostic disable-next-line: duplicate-set-field
        _ENV.loadfile = function (path, ...)
            local loader = package.nebluaModule[path]
            if loader ~= nil and loader.loader ~= nil then
                return loader.loader
            else
                return originalLoadFile(path, ...)
            end
        end

        _ENV.requireText = function (path)
            return package.loaded[path]
        end
    end

    _ENV.__NEBLUA_INSTALLED = true

    -- Error handler for xpcall
    local errorHandler = function (err)
        local srcName = debug.getinfo(1).short_src:gsub("[^%w]", "%%%0")
        local pattern = srcName .. ":(%d+):"
        local loaderLineOffset = -1

        local message = debug.traceback(err, 2):gsub(pattern, function (line)
            local lineNumber = tonumber(line)

            local loaderLine = -1
            local loaderName = nil
            for name, loader in pairs(package.nebluaModule) do
                if
                    loader.line ~= nil
                    and loaderLine < loader.line
                    and loader.line < lineNumber
                then
                    loaderLine = loader.line
                    loaderName = name
                end
            end

            -- stylua: ignore
            return loaderName .. ":" .. (lineNumber - loaderLine + loaderLineOffset) .. ":"
        end)

        return message
    end

    

    local loader = bundlerSearcher("./entry.iconCursor")
    if loader == nil then
        error("Cannot find entry point: " .. "./entry.iconCursor")
    end

    local result =
        table.pack(xpcall(loader, errorHandler, "./entry.iconCursor", ...))
    local success = result[1]

        rollbackLoaded()
    rollbackPreload()
    rollbackSearchers()


    -- print error to stdout and re-throw
    if not success then
        if true then
            print(result[2])
        else
            io.stderr:write(result[2])
        end
        error("Error occurred in bundled file.")
    end

    return table.unpack(result, 2)
end)(...)
