name: Build and Test


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Run test
        run: mise run test


  ensure-build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Ensure build
        run: |
          mise run build
          test -z "$(git diff --name-only)"


  check-manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Check manifests
        run: mise run check:manifest
