name: Build and Test


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Run test
        run: mise run test


  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Check manifests
        run: mise run check:manifest

      - name: Build
        run: mise run build

      - uses: actions/upload-artifact@v4
        with:
          name: scripts
          path: dist
          retention-days: 7
