name: Run Tests

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: leafo/gh-actions-lua@v10
        with:
          lua-version: 5.4

      - name: Run test
        run: make test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        target:
          - '{
              "name": "psd",
              "output": "./dist/Export as psd.lua"
            }'
          - '{
              "name": "icon-and-cursor",
              "output": "./dist/Export as ico cur ani.lua"
            }'
          - '{
              "name": "lcd-pixel-filter",
              "output": "./dist/LCD Pixel Filter.lua"
            }'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: leafo/gh-actions-lua@v10
        with:
          lua-version: 5.4

      - name: Build
        run: |
          make clean
          make build-${{ fromJSON(matrix.target).name }}

      - uses: ./.github/actions/use-script-manifest
        id: manifest
        with:
          filename: ${{ fromJSON(matrix.target).output }}

      - name: Check package manifest
        run: |
          echo 'name:        ${{ steps.manifest.outputs.name }}'
          echo 'description: ${{ steps.manifest.outputs.description }}'
          echo 'version:     ${{ steps.manifest.outputs.version }}'
          echo 'author:      ${{ steps.manifest.outputs.author }}'
          echo 'license:     ${{ steps.manifest.outputs.license }}'
          echo 'homepage:    ${{ steps.manifest.outputs.homepage }}'
